id: Office 365 Search and Delete V2
version: -1
name: Office 365 Search and Delete V2
description: Run a ComplianceSearch on Office 365 and delete the results.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 311996c7-2e57-44ae-8079-5107b44fc441
    type: start
    task:
      id: 311996c7-2e57-44ae-8079-5107b44fc441
      version: -1
      name: ""
      description: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 04541c29-c796-40cf-83b1-9b3ee0e380d7
    type: regular
    task:
      id: 04541c29-c796-40cf-83b1-9b3ee0e380d7
      version: -1
      name: Create compliance search
      description: Create compliance search in the Security & Compliance Center.
      script: '|||o365-sc-new-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      allow_not_found_exchange_locations:
        complex:
          root: inputs.allow_not_found_exchange_locations
      case:
        complex:
          root: inputs.case
      description:
        complex:
          root: inputs.description
      exchange_location:
        complex:
          root: inputs.exchange_location
      exchange_location_exclusion:
        complex:
          root: inputs.exchange_location_exclusion
      kql:
        complex:
          root: inputs.kql
      public_folder_location:
        complex:
          root: inputs.public_folder_location
      search_name:
        complex:
          root: inputs.search_name
      share_point_location:
        complex:
          root: inputs.public_folder_location
      share_point_location_exclusion:
        complex:
          root: inputs.share_point_location_exclusion
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: d0dbe5c3-9916-48da-8581-29af4ecefdcf
    type: regular
    task:
      id: d0dbe5c3-9916-48da-8581-29af4ecefdcf
      version: -1
      name: ews-o365-get-compliance-search
      description: Gets compliance search by name from the Security & Compliance Center.
      script: '|||o365-sc-get-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all_results: {}
      export: {}
      limit: {}
      search_name:
        complex:
          root: inputs.search_name
      statistics:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 2ab30693-f1f8-40be-84a5-9a868439b1cb
    type: condition
    task:
      id: 2ab30693-f1f8-40be-84a5-9a868439b1cb
      version: -1
      name: Purge Compliance Search Results?
      description: Purge Compliance Search Results?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Ignore:
      - "9"
      Purge:
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2876370b-83e8-4e38-86b2-a24865376792
    type: title
    task:
      id: 2876370b-83e8-4e38-86b2-a24865376792
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -200,
          "y": 1665
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 8c83e54e-e005-4f89-8aab-ec669b74bd77
    type: regular
    task:
      id: 8c83e54e-e005-4f89-8aab-ec669b74bd77
      version: -1
      name: Get search action
      description: Gets compliance search action from the Security & Compliance Center.
      script: '|||o365-sc-get-search-action'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      export:
        simple: "true"
      limit: {}
      results: {}
      search_action_name:
        complex:
          root: O365.SecurityAndCompliance.ContentSearch.SearchAction
          accessor: Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 677ab01d-5dbb-46e2-8ea1-cf5a06779997
    type: regular
    task:
      id: 677ab01d-5dbb-46e2-8ea1-cf5a06779997
      version: -1
      name: ews-o365-remove-compliance-search
      description: Remove the compliance search
      script: '|||ews-o365-remove-compliance-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      search-name:
        complex:
          root: EWS
          accessor: ComplianceSearch.Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -200,
          "y": 1460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: c98fa3b0-6b65-4fca-87b2-e0d29da1d772
    type: playbook
    task:
      id: c98fa3b0-6b65-4fca-87b2-e0d29da1d772
      version: -1
      name: O365 - Security And Compliance - Search Start
      playbookName: O365 - Security And Compliance - Search Start
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      search_name:
        complex:
          root: inputs.search_name
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: b63e47c4-7054-4586-8994-8a60cf9d0e6d
    type: condition
    task:
      id: b63e47c4-7054-4586-8994-8a60cf9d0e6d
      version: -1
      name: Choose Hard delete / Soft delete
      type: condition
      iscommand: false
      brand: ""
      description: 'Choose which type of delete (Purge) you would like to execute on search results.'
    nexttasks:
      Hard delete:
      - "15"
      Soft delete:
      - "14"
    separatecontext: false
    defaultassigneecomplex:
      simple: admin
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: e4351a7c-4157-4c74-8fa2-58c49b8b5d30
    type: playbook
    task:
      id: e4351a7c-4157-4c74-8fa2-58c49b8b5d30
      version: -1
      name: O365 - Security And Compliance - Search Action
      playbookName: O365 - Security And Compliance - Search Action
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      purge_type:
        simple: SoftDelete
      search_action:
        simple: Purge
      search_name:
        complex:
          root: inputs.search_name
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: b2d8e111-33eb-4fc0-8356-5e87e8385f03
    type: playbook
    task:
      id: b2d8e111-33eb-4fc0-8356-5e87e8385f03
      version: -1
      name: O365 - Security And Compliance - Search Action
      playbookName: O365 - Security And Compliance - Search Action
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      purge_type:
        simple: SoftDelete
      search_action:
        simple: Purge
      search_name:
        complex:
          root: inputs.search_name
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1680,
        "width": 1060,
        "x": -200,
        "y": 50
      }
    }
  }
inputs:
- key: search_name
  value: {}
  required: true
  description: ' The name of the compliance search.'
  playbookInputQuery:
- key: case
  value: {}
  required: false
  description: ' The name of a Core eDiscovery case to associate with the new compliance
    search.'
  playbookInputQuery:
- key: kql
  value: {}
  required: false
  description: Text search string or a query that is formatted using the Keyword Query
    Language (KQL).
  playbookInputQuery:
- key: description
  value: {}
  required: false
  description: ' Description of the compliance search.'
  playbookInputQuery:
- key: allow_not_found_exchange_locations
  value: {}
  required: false
  description: Whether to include mailboxes other than regular user mailboxes in the
    compliance search. Default is "false".
  playbookInputQuery:
- key: exchange_location
  value: {}
  required: false
  description: 'Comma-separated list of mailboxes/distribution groups to include,
    or you can use the value "All" to include all. '
  playbookInputQuery:
- key: exchange_location_exclusion
  value: {}
  required: false
  description: Comma-separated list of mailboxes/distribution groups to exclude when
    you use the value "All" for the exchange_location parameter.
  playbookInputQuery:
- key: public_folder_location
  value: {}
  required: false
  description: Comma-separated list of public folders to include, or you can use the
    value "All" to include all.
  playbookInputQuery:
- key: share_point_location
  value: {}
  required: false
  description: Comma-separated list of SharePoint online sites to include. You can
    identify the sites by their URL value, or you can use the value "All" to include
    all sites.
  playbookInputQuery:
- key: share_point_location_exclusion
  value: {}
  required: false
  description: 'Comma-separated list of SharePoint online sites to exclude when you
    use the value "All" for the share_point_location argument. You can identify the
    sites by their URL value. '
  playbookInputQuery:
outputs: []
fromversion: 5.5.0
tests:
- O365-SecurityAndCompliance-Test
