id: O365 - Security And Compliance - Search Action
version: -1
name: O365 - Security And Compliance - Search Action
description: This playbook intend to create new search action in security and compliance
  and than wait to search action to complete.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 10f32136-0872-4c2f-80de-6c736e896561
    type: start
    task:
      id: 10f32136-0872-4c2f-80de-6c736e896561
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: bf288d5d-d5df-4452-8ebb-a5d2727c63bd
    type: regular
    task:
      id: bf288d5d-d5df-4452-8ebb-a5d2727c63bd
      version: -1
      name: Create search action
      description: After you create a content search using the !o365-sc-new-search
        command and run it using the !o365-sc-start-search command, you assign a search
        action to the search using the !o365-sc-new-search-action command.
      script: '|||o365-sc-new-search-action'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      action:
        complex:
          root: inputs.search_action
      purge_type:
        complex:
          root: inputs.purge_type
      search_name:
        complex:
          root: inputs.search_name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 376d45ea-b5b9-41d8-8b45-c7613116c0a3
    type: playbook
    task:
      id: 376d45ea-b5b9-41d8-8b45-c7613116c0a3
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: O365.SecurityAndCompliance.ContentSearch.SearchAction
          accessor: Name
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: search_action_name
      PollingCommandName:
        simple: o365-sc-get-search-action
      Timeout:
        simple: "10"
      dt:
        simple: O365.SecurityAndCompliance.ContentSearch.SearchAction(val.Status &&  val.Status
          == "InProgress" || val.Status == "Starting" || val.Status == "Purging")
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 8b7a6246-14a6-438c-8c59-8f7e011aa9a5
    type: title
    task:
      id: 8b7a6246-14a6-438c-8c59-8f7e011aa9a5
      version: -1
      name: Search action completed.
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: search_name
  value: {}
  required: true
  description: The name of the compliance search.
  playbookInputQuery:
- key: search_action
  value: {}
  required: true
  description: Search action to perform - Preview/Purge.
  playbookInputQuery:
- key: purge_type
  value: {}
  required: false
  description: Choose purge type if purge action chose - Soft Delete/Hard Delete.
  playbookInputQuery:
outputs:
- contextPath: O365.SecurityAndCompliance.ContentSearch.SearchAction.Name
  description: Security and compliance search action name.
  type: string
fromversion: 5.5.0
tests:
- O365-SecurityAndCompliance-Test
