id: O365 - Security And Compliance - search start - Generic polling
version: -1
name: O365 - Security And Compliance - search start - Generic polling
description: This playbook intend to start search in security and compliace and than
  wait to search to complete.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ca5dfed0-e804-46aa-89ab-6f9da00ff115
    type: start
    task:
      id: ca5dfed0-e804-46aa-89ab-6f9da00ff115
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5e2cdd46-d2c8-47fa-8e3d-08d41f1dc9d2
    type: playbook
    task:
      id: 5e2cdd46-d2c8-47fa-8e3d-08d41f1dc9d2
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${inputs.Search name}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: search_name
      PollingCommandName:
        simple: o365-sc-get-search
      Timeout:
        simple: "10"
      dt:
        simple: O365.SecurityAndCompliance.ContentSearch.Search(val.Status &&  val.Status
          != "Completed")
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 9438dcb4-53e3-430b-8a20-42584b4be4bb
    type: title
    task:
      id: 9438dcb4-53e3-430b-8a20-42584b4be4bb
      version: -1
      name: Search completed
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: ef220e85-6cf1-4330-8920-f19099af896e
    type: regular
    task:
      id: ef220e85-6cf1-4330-8920-f19099af896e
      version: -1
      name: Start search
      description: Start stopped, completed or not started compliance search in the
        Security & Compliance Center.
      script: '|||o365-sc-start-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      search_name:
        simple: ${inputs.Search name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Search name
  value: {}
  required: true
  description: The name of the compliance search.
  playbookInputQuery: null
outputs: []
sourceplaybookid: b9d8fe6c-1af4-4780-81a5-3de32cfc118a
fromversion: 5.5.0
tests:
 - O365-SecurityAndCompliance-Test
